[package]
name = "ckks_homomorphic_encryption"
version = "0.1.0"
edition = "2021"

[dependencies]
ff = "0.9"  # Finite field arithmetic
rand = "0.8"  # Random number generation
num-bigint = "0.4"  # For large integer support (could be useful for mod operations)
